### PR TITLE
Chained HOC

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
This should pass...

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
@villesau Do you have any ideas how to make this pass?

The issue is that whenever we chain multiple higher-order components together we're losing information regarding required props i.e. You can omit them and Flow won't pick-up on it. So I've added a test that _intentionally_ omits `requiredProp` and added `$ExpectError`, but Flow _doesn't_  error, as expected.

This demonstration is with respect to `@material-ui/core` (`withStyles` & `withTheme`) as it makes sense to chain these methods. However, @jmtoung has created a thorough repository reproducing this issue when chaining `withStyles` against `react-redux`'s `connect` (https://github.com/jmtoung/flow-hoc-issue).

I've _tried_ to use the same HOC pattern as you've done with `react-redux`'s libdefs, however it's very possible I've messed up. If you have any ideas how we could address this, that would be hugely appreciated.

**Comment by Benjamin-Dobell** [comment]
@cesardeazevedo re: https://github.com/flow-typed/flow-typed/pull/2632#discussion_r212813677

I just had a crack at swapping `$ElementConfig<Component>` out for `$ElementConfig<$Supertype<Component>>` but once I do I get a lot of other errors elsewhere. It may well be that other flow types are messed up, but issues were being silently ignored.

When I get some more time I'll come back to this, however if anyone else has time to take a look and make this test pass then that would be fantastic.

**Comment by cesardeazevedo** [comment]
Hi @Benjamin-Dobell, i made it pass. 🎉

I wrapped both `$ElementConfig<Component>` with `$ElementConfig<$Supertype<Component>>`, and i started getting new errors as you said, i started investigating the errors and i realized that the `classes` and `theme` props on tests was defined  by `{}`, which flow wasn't be able to inferred.

So i think all these new errors that `$Supertype` just shown was likely to be correct, so i changed all references of `{classes: {}, theme: {}}` to `{classes: *, theme: *}`, and lots of errors disappear, with only a few remaining related to the injection of the prop types.

Looking at your code you are defining the injection props as follows.

```js
  declare export type WithStyles = {
    classes: { +[string]: string },
    innerRef: React$Ref<React$ElementType> | {current: null | React$ElementRef<React$ElementType>}
  };
```

And since the injected props are been diffed with `$Diff<React$ElementConfig<$Supertype<WrappedComponent>>, WithStyles>`
the `$Diff<A, B>` function will throw a error if you try to remove a property defined in `B` that doesn't exists in `A`.

This is what the docs says regarding injecting props with a high order component
 (https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component)

> Note: If foo does not exist in Props you will get an error! $Diff<{}, { foo: number }> will be an error. To work around this use a union with void, see: $Diff<{}, { foo: number | void }>. An optional prop will not completely remove foo. $Diff<{ foo: number }, { foo?: number }> is { foo?: number } instead of {}.

I changed the injected properties to be unied with a `void` as follows

```js
  declare export type WithStyles = {
    classes: void | { +[string]: string },
    innerRef: void | React$Ref<React$ElementType> | {current: null | React$ElementRef<React$ElementType>}
  };
```

And everything passed. 🎉

**Comment by Benjamin-Dobell** [comment]
@cesardeazevedo Nice work!

If you'd like, feel free to submit a PR either here (`chained-hoc` branch) or directly to flow-typed. Otherwise, I'll happily set about recreating the changes.

**Review by jmtoung — COMMENTED** [review]
Great work guys. Thanks so much!

**Comment by Benjamin-Dobell** [comment]
Unfortunately, I've found the `void | ` approach doesn't really do what we want in real-world apps, as every time you access `this.props.classes` you have to check that it's non-void, when in reality it can never be `null`. 😞

I've updated the tests demonstrating the problem.

**Comment by Benjamin-Dobell** [comment]
I'm presently trying something like:

```
  declare export type WithStyles = {|
    classes: { +[string]: string },
    innerRef: React$Ref<React$ElementType> | {current: null | React$ElementRef<React$ElementType>}
  |};

  declare type WithStylesHOC = {|
    classes: void | { +[string]: string },
    innerRef: void | React$Ref<React$ElementType> | {current: null | React$ElementRef<React$ElementType>}
  |};

  declare module.exports: (
    stylesOrCreator: StyleRules | StyleRulesCallback,
    options?: WithStylesOptions,
  ) => <WrappedComponent: React$ComponentType<*>>(
    Component: WrappedComponent
  ) => React$ComponentType<$Diff<React$ElementConfig<$Supertype<WrappedComponent>>, WithStylesHOC>>;
```

To work around the issue, but running into more issues 😞

**Comment by cesardeazevedo** [comment]
You shouldn't use the `WithStyles` directly in your component, this type is only meant to be "diffed" from the actual type, that's why the `void`, maybe extracting the classes type would be better.

```js
declare export type Classes = {
  +[string]: string,
}

declare export type WithStyles = {
  classes: void | Classes,
  innerRef: void | React$Ref<React$ElementType> | {current: null | React$ElementRef<React$ElementType>}
};

class TestComponent extends React.Component<{
  classes: Classes,
}> {
  render() {
    const root = this.props.classes.root
  }
}

```

**Comment by Benjamin-Dobell** [comment]
Ideally `WithStyles` and `WithTheme` should be exported as they are in material-ui's official TypeScript types. They were also exported in the past directly from the material-ui project (pre 1.0) when they maintained Flow types within the material-ui project.

However, I agree with the sentiment with respect to not exporting the types containing `void |`, and simply using them internally. That's why in my comment above I mentioned I was attempting to use `WithStylesHOC` internally, but exporting `WithStyles` (without the `void |`) types.

To my surprise, I'm having trouble getting that working. It's something to do with `innerRef`, because if I omit it from `WithStyles` and `WithThemes` it works 😕 I don't know if anyone out there actually uses `innerRef` anyway, so I can probably omit it. However, I'd love to understand why it's not working.

**Comment by Benjamin-Dobell** [comment]
...and as I write that. I work it out.

**Comment by Benjamin-Dobell** [comment]
Merged upstream as https://github.com/flow-typed/flow-typed/pull/2677

**Pull request closed without merging**
